variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: "tcp://docker:2375"
    MYSQL_ROOT_PASSWORD: app
    DEVELOPMENT_BRANCH: "v6.4.0.0"
    PLATFORM_BRANCH: "v6.4.0.0"
    ASSISTANT_BRANCH: "master"
    WEB_DOCUMENT_ROOT: $CI_PROJECT_DIR/development/public
    DEV_IMAGE: shopware/development:7.4-composer-2

stages:
    - Static analyzes
    - PHPUnit

default:
    image: $DEV_IMAGE
    before_script:
        - zip -rq plugin.zip .
        - git clone http://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.shopware.com/shopware/6/product/development.git --branch $DEVELOPMENT_BRANCH
        - rm -rf development/platform
        - git clone http://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.shopware.com/shopware/6/product/platform.git development/platform --branch $PLATFORM_BRANCH
        - git clone http://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.shopware.com/shopware/6/services/migration-assistant.git development/custom/plugins/SwagMigrationAssistant --branch $ASSISTANT_BRANCH
        - unzip -q plugin.zip -d development/custom/plugins/SwagMigrationOxid
        - cd development
        - cp -v dev-ops/gitlab/.psh.yaml.override .
        - /entrypoint supervisord > /dev/null 2>&1 &

PHP analyze:
    stage: Static analyzes
    services:
        -   name: mysql:5.7
            alias: mysql
    script:
        - ./psh.phar init
        - php bin/console plugin:install --activate SwagMigrationAssistant
        - php bin/console plugin:install --activate SwagMigrationOxid
        - cd $CI_PROJECT_DIR/development/custom/plugins/SwagMigrationOxid
        - php ../../../dev-ops/analyze/vendor/bin/ecs check --config=../../../vendor/shopware/platform/easy-coding-standard.php src tests
        - php ../../../dev-ops/analyze/vendor/bin/ecs check --fix --config=easy-coding-standard.php
        - bin/static-analyze.sh

PHPUnit (MariaDB):
   stage: PHPUnit
   needs: [PHP analyze]
   services:
       -   name: mariadb:10.3.28
           alias: mysql
   script:
       - ./psh.phar init
       - php bin/console plugin:install --activate SwagMigrationAssistant
       - php bin/console plugin:install --activate SwagMigrationOxid
       - composer dump-autoload -d custom/plugins/SwagMigrationOxid
       - composer dump-autoload -d custom/plugins/SwagMigrationAssistant
       - touch custom/plugins/SwagMigrationAssistant/vendor/composer/InstalledVersions.php
       - touch custom/plugins/SwagMigrationOxid/vendor/composer/InstalledVersions.php
       - ./psh.phar init-test-databases
       - php -d pcov.enabled=1 -d pcov.directory=$CI_PROJECT_DIR
           vendor/bin/phpunit
           --configuration custom/plugins/SwagMigrationOxid/phpunit.xml.dist
           --log-junit build/artifacts/phpunit.junit.xml
           --colors=never
           --coverage-clover build/artifacts/phpunit.clover.xml
           --coverage-html build/artifacts/phpunit-coverage-html
           --coverage-text
   coverage: '/^\s*Lines:\s*(\d+(?:\.\d+)?%)/'
   artifacts:
       paths:
           - development/build/artifacts/phpunit.clover.xml
       reports:
           junit: development/build/artifacts/phpunit.junit.xml
   parallel:
       matrix:
           -   DEV_IMAGE: shopware/development:8.0-composer-2
           -   DEV_IMAGE: shopware/development:7.4-composer-2
